require("codeium")
vim.keymap.set("i", "<leader><CR>", function()
	return vim.fn["codeium#Accept"]()
end)
vim.keymap.set("i", "<leader>]", function()
	return vim.fn["codeium#CycleCompletions"](1)
end)
vim.keymap.set("i", "<leader>[", function()
	return vim.fn["codeium#CycleCompletions"](-1)
end)
vim.keymap.set("i", "<leader>c", function()
	return vim.fn["codeium#Clear"]()
end)
vim.keymap.set("i", "<C-c>", "<Esc>")
