return {
	-- "supermaven-inc/supermaven-nvim",
	-- config = function()
	-- 	local maven = require("supermaven-nvim")
	-- 	local api = require("supermaven-nvim.api")
	-- 	api.stop()
	-- 	maven.setup({
	-- 		keymaps = {
	-- 			accept_suggestion = "<Tab>",
	-- 			clear_suggestion = "<C-]>",
	-- 			accept_word = "<C-j>",
	-- 		},
	--
	-- 		-- ignore_filetypes = { cpp = true }, -- or { "cpp", }
	-- 		color = {
	-- 			suggestion_color = "#b16286",
	-- 			cterm = 244,
	-- 		},
	-- 		log_level = "info",
	-- 		disable_inline_completion = false,
	-- 		disable_keymaps = false,
	-- 		-- Condition to check for stopping supermaven, `true` to stop
	-- 		condition = function()
	-- 			return true
	-- 		end
	-- 	})
	-- end
}
