-------------------
-- Surround Text --
-------------------
vim.keymap.set({ "n","v" }, "S", "<nop>")
vim.keymap.set("v", "S\"", "di\"\"<esc>P", { desc = "Surround w/ \"\"" })
vim.keymap.set("v", "Sq", "di\"\"<esc>P", { desc = "Surround w/ \"\"" })
vim.keymap.set("v", "S'", "di''<esc>P", { desc = "Surround w/ ''" })
vim.keymap.set("v", "SQ", "di''<esc>P", { desc = "Surround w/ ''" })
vim.keymap.set("v", "S`", "di``<esc>P", { desc = "Surround w/ ``" })
vim.keymap.set("v", "SB", "di``<esc>P", { desc = "Surround w/ ``" })
vim.keymap.set("v", "S<", "di<><esc>P", { desc = "Surround w/ <>" })
vim.keymap.set("v", "St", "di<><esc>P", { desc = "Surround w/ <>" })
vim.keymap.set("v", "S>", "di</><esc>P", { desc = "Surround w/ </>" })
vim.keymap.set("v", "ST", "di</><esc>P", { desc = "Surround w/ </>" })
vim.keymap.set("v", "S{ ", "di{}<esc>P", { desc = "Surround w/ { }" })
vim.keymap.set("v", "S<leader>{", "di{  }<esc>hP", { desc = "Surround w/ {  }" })
vim.keymap.set("v", "S(", "di()<esc>P", { desc = "Surround w/ ()" })
vim.keymap.set("v", "S[", "di[]<esc>P", { desc = "Surround w/ []" })
vim.keymap.set("v", "S<leader>[", "di[  ]<esc>hP", { desc = "Surround w/ [  ]" })
vim.keymap.set("v", "Sl", "di[[]]<esc>hP", { desc = "Surround w/ [[]]" })
vim.keymap.set("v", "S<leader>l", "di[[  ]]<esc>hhP", { desc = "Surround w/ [[  ]]" })
vim.keymap.set("v", "S<leader>L", "di[[  ]];<esc>hhP", { desc = "Surround w/ [[  ]];" })
vim.keymap.set("v", "S*", "di**<esc>P", { desc = "Surround w/ **" })
vim.keymap.set("v", "S_", "di__<esc>P", { desc = "Surround w/ __" })
vim.keymap.set("v", "Si", "di__<esc>P", { desc = "Surround w/ __" })
vim.keymap.set("v", "Sb", "di****<esc>hP", { desc = "Surround w/ ****" })
vim.keymap.set("v", "SI", "di_****_<esc>hhP", { desc = "Surround w/ _****_" })
vim.keymap.set("v", "SB", "di_****_<esc>hhP", { desc = "Surround w/ _****_" })
